class CityNamesList {
  static List<String> majorCities = [
    'Amsterdam',
    'Athens',
    'Bangalore',
    'Bangkok',
    'Beijing',
    'Berlin',
    'Birmingham',
    'Brisbane',
    'Brussels',
    'Bucharest',
    'Budapest',
    'Buenos Aires',
    'Cairo',
    'Cardiff',
    'Chennai',
    'Chicago',
    'Copenhagen',
    'Dallas',
    'Delhi',
    'Dhaka',
    'Dubai',
    'Dublin',
    'Edinburgh',
    'Frankfurt',
    'Geneva',
    'Glasgow',
    'Houston',
    'Hyderabad',
    'Istanbul',
    'Islamabad',
    'Jakarta',
    'Johannesburg',
    'Karachi',
    'Kolkata',
    'Kuala Lumpur',
    'Lagos',
    'Lahore',
    'Leeds',
    'Lisbon',
    'Liverpool',
    'London',
    'Los Angeles',
    'Madrid',
    'Manchester',
    'Melbourne',
    'Mexico City',
    'Montreal',
    'Moscow',
    'Mumbai',
    'Nairobi',
    'New York',
    'Oslo',
    'Paris',
    'Philadelphia',
    'Phoenix',
    'Prague',
    'Rio de Janeiro',
    'Rome',
    'Rotterdam',
    'São Paulo',
    'Seoul',
    'Singapore',
    'Sydney',
    'Tokyo',
    'Toronto',
    'Vancouver',
    'Vienna',
    'Warsaw',
    'Zurich'
  ];
}
